### ISSUE TITLE
bug report: sustains look *really* wack

### ISSUE THREAD

**Issue by Leather128** [TheZoroForce240/FNF-Modcharting-Tools#10]
![image](https://user-images.githubusercontent.com/81660872/221067974-a93bb59a-8cca-443a-8b65-9d363a1ab0fd.png)

yeah idk why they stretch like this but it'd be kinda cool and stuff if it didn't (also for some reason my performance dies but that might be another issue idk)

**Comment by Vortex2Oblivion** [comment]
when i was messing around with it the other day it was fine, maybe a linux thing?

**Comment by Leather128** [comment]
that would be a really weird bug for linux specifically (also either way a bug *is* a bug y'know)

**Comment by Vortex2Oblivion** [comment]
yea
i checked on windows and it seems to be fine

**Comment by Vortex2Oblivion** [comment]
![image](https://user-images.githubusercontent.com/73261680/221254050-857707c1-6428-45fd-b8bc-2da36eaedc70.png)
nevermind

**Comment by TheZoroForce240** [comment]
![Screenshot 2023-02-24 194441](https://user-images.githubusercontent.com/86524550/221276267-bfe8c480-4138-4d44-baa3-bb267c8988b4.png)
should be fixed now, just lemme know if theres still any issues

**Comment by Leather128** [comment]
![image](https://user-images.githubusercontent.com/81660872/221371136-939e25e0-ebd6-448f-9bb7-b2078ca85124.png)
uh it's still broken my sir

**Comment by TheZoroForce240** [comment]
maybe try updating haxeflixel, cuz the sustains are supposed to be transparent and support for alpha on triangles was added recently, it could be something to do with that?

**Comment by TheZoroForce240** [comment]
if you mean specifically the sustain end being slightly stretched thats normal and ive tried fixing it before but had issues with reversing the scroll breaking it, not sure whats going on with the gap though
